### ISSUE TITLE
[feature] Add images to the pokemon

### ISSUE THREAD

**Issue by KarlHeitmann** [Strike2-ux/PokeApi-Node-and-Express#3]
The `allPokemon` constant has a list of pokemons, with it's `id`, `nombre` and `tipo`. Add `image_url`that has the url to get the image of the pokemon. In order for this feature to work, you will need to serve the image assets to be served on express.

**Comment by Strike2-ux** [comment]
@patcont @KarlHeitmann if you can see, the new update, I did what you ask, remember always the variables need to be write in English, for professional purposes. The links of the images are official from the pokemon company.
